#ifdef REGEX_MACROS_DEF_H
#undef __BACKSLASH
#undef __ANY_CHAR
#undef __DOUBLEQ
#undef __SINGLEQ
#undef __CARROT
#undef __LSQUAREB
#undef __RSQUAREB
#undef __LCURVEDB
#undef __RCURVEDB
#undef __ZERO_OR_MORE
#undef __ZERO_OR_ONE
#undef __ONE_OR_MORE
#undef __TO
#undef __OR
#undef ___OR
#undef ___AND
#undef __ELSE
#undef ___ELSE
#undef __ELIF
#undef __ONE_OR_MORE_OF
#undef __STRING_PREFIX
#undef __ANY_CHAR_THATS_NOT_A_NEWLINE
#undef __NEWLINE
#undef __WHITESPACE
#undef __ANY
#undef __ANY_OF
#undef __NONE_OF
#undef __ZERO_OR_MORE_OF
#undef __ZERO_OR_ONE_OF
#undef __PYTHON_SYMBOLS
#undef __NOCAPTURE_START
#undef __NOCAPTURE
#undef __STRING_NOCAPTURE
#undef ___STRING
#undef ___DOC_STRING
#undef REGEX_MACROS_DEF_H
#endif
